version: "3.7"

services:
  neo4j:
    image: neo4j:4.4.3
    ports:
      - 7687:7687
      - 7474:7474
    volumes:
      - $HOME/neo4j/data:/data
    environment:
      NEO4J_AUTH: "neo4j/VzV3h2NM"
#      NEO4J_dbms_memory_heap_initial__size: 512M
#      NEO4J_dbms_memory_heap_max__size: 512M
    networks:
      - default
