version: "3.7"

services:
  app:
    build: .
    ports:
      - 80:8080
    environment:
      NEO4J_HOST: "${NEO4J_HOST}"
      NEO4J_PORT: "${NEO4J_PORT}"
      NEO4J_USERNAME: "${NEO4J_USERNAME}"
      NEO4J_PASSWORD: "${NEO4J_PASSWORD}"
      ES_HOST: "${ES_HOST}"
      ES_PORT: "${ES_PORT}"
    networks:
      - default
