spring:
  neo4j:
    url: bolt://${NEO4J_HOST}:${NEO4J_PORT}
    authentication:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}

elasticsearch:
  host: ${ES_HOST}
  port: ${ES_PORT}