version: "3.7"

services:
  es:
    build: ./es-docker/
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - $HOME/es/data:/usr/share/elasticsearch/data
      - $HOME/es/logs:/usr/share/elasticsearch/logs
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms2g -Xmx2g
    networks:
      - default